name: finance_manager
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
 

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  cloud_firestore: ^4.17.5
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

